Importing Numpy Library

In [18]:
import numpy as np

**Matrix Addition**

Two Matrices can be added only if they have the same shape

In [19]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [20]:
print(A)

[[2 3]
 [4 5]]


In [21]:
print(B)

[[6 7]
 [8 9]]


In [22]:
A.shape

(2, 2)

In [23]:
B.shape

(2, 2)

Adding two Matrices

In [24]:
sum = A + B

In [25]:
print(sum)

[[ 8 10]
 [12 14]]


In [26]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [27]:
print(matrix_1)

[[0 6 5]
 [4 1 9]
 [2 1 1]]


In [28]:
print(matrix_2)

[[ 4 11  8]
 [ 8 15  7]
 [16 10 12]]


In [29]:
sum = np.add(matrix_1, matrix_2)

In [30]:
print(sum)

[[ 4 17 13]
 [12 16 16]
 [18 11 13]]


In [31]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [32]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different

**Matrix Subtraction**

In [33]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [34]:
print(A)

[[2 3]
 [4 5]]


In [35]:
print(B)

[[6 7]
 [8 9]]


In [36]:
difference = A - B

In [37]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [38]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [39]:
print(matrix_1)

[[5 4 5]
 [5 9 6]
 [5 1 1]]


In [40]:
print(matrix_2)

[[ 2 14  1]
 [18 13  4]
 [15  9 19]]


In [41]:
diff = np.subtract(matrix_1, matrix_2)

In [42]:
print(diff)

[[  3 -10   4]
 [-13  -4   2]
 [-10  -8 -18]]


**Multiplying a matrix by a scalar**

In [43]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[6 0 3 7]
 [5 9 6 7]
 [9 7 6 1]
 [5 3 6 8]]


In [44]:
product = np.multiply(x,y)
prod=x*y
print(prod)

[[30  0 15 35]
 [25 45 30 35]
 [45 35 30  5]
 [25 15 30 40]]


In [45]:
print(product)

[[30  0 15 35]
 [25 45 30 35]
 [45 35 30  5]
 [25 15 30 40]]


**Multiplying 2 Matrices**

In [46]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [47]:
print(matrix_3)

[[1 2 3]
 [3 3 0]
 [1 2 4]]


In [48]:
print(matrix_4)

[[0 1 3 1]
 [0 3 3 3]
 [0 3 4 0]]


In [49]:
product = np.dot(matrix_3, matrix_4)

In [50]:
print(product)

[[ 0 16 21  7]
 [ 0 12 18 12]
 [ 0 19 25  7]]


In [51]:
product.shape

(3, 4)

In [52]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [53]:
product = np.dot(matrix_3, matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

**Element wise Matrix Multiplication**

In [54]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [55]:
print(matrix_3)

[[3 3 2]
 [2 3 2]
 [2 3 0]]


In [56]:
print(matrix_4)

[[1 0 2]
 [4 4 2]
 [2 3 2]]


In [57]:
product = np.multiply(matrix_3, matrix_4)

In [58]:
print(product)

[[ 3  0  4]
 [ 8 12  4]
 [ 4  9  0]]


In [59]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [60]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 