In [1]:
import numpy as np

Creating a Matrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.17080921 0.3538522  0.13506806]
 [0.16934517 0.32965194 0.96725482]
 [0.24577436 0.49827638 0.1388263 ]]


In [7]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[60 51 28 32 96]
 [95 77 71  7 27]
 [31 81 98 75 41]
 [67 70 88 41 35]]


Matrix with all the values as 1

In [8]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [10]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [11]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [13]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [15]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[51 19  1 46 30]
 [18 67 42 57 27]
 [90 13 69 93  2]
 [40 90 83 23 97]]


In [16]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[51 18 90 40]
 [19 67 13 90]
 [ 1 42 69 83]
 [46 57 93 23]
 [30 27  2 97]]
